### PR TITLE
Unittest

### PR DESCRIPTION
**Pull request by zach1590**
Started writing some unittests for the routes

Should also serve as good starting point for how to write tests in the future of new members

### CODE REVIEW

**Comment by jeffstjean** [comment]
Looks good. I've been working on decoupling the routes from their business logic (see: [CommandRoute](https://github.com/UWO-Aero-Design/gnd-station/blob/feature/usb_tool/api/routes/CommandRoute.js#L10-L21) on #47) so we won't need to test the routes as much as the interfaces or objects that they interact with.

We should take a look at running these tests in Docker [using the existing image](https://docs.docker.com/language/nodejs/run-tests/) so they're running in the same environment.

Also, don't worry about making the commands route tests past because I just overhauled that in my recent #47.

**Review by jeffstjean — CHANGES_REQUESTED** [review]
Meant to submit previous comment as feedback. Can you look into getting these tests running through Docker? I'm hoping to reuse the same image with some small modification (see [here](https://docs.docker.com/language/nodejs/run-tests/#multi-stage-dockerfile-for-testing)). Not sure how that changes the startup command (I'm hoping it's something similar to `docker compose up api` for prod and `docker compose up api:test` to run tests)

**Comment by jeffstjean** [comment]
Sounds like we can leverage [multi-stage builds](https://docs.docker.com/compose/compose-file/compose-file-v3/#target) (another example [here](https://stackoverflow.com/questions/53093487/multi-stage-build-in-docker-compose)) to achieve this. If possible, I would prefer the dev/prod environment to still be brought up with `docker compose up api` and the testing framework as some variant of that. Not sure if it's possible though.

**Comment by jeffstjean** [comment]
Found one more example that's probably easiest to follow: https://codefresh.io/docker-tutorial/node_docker_multistage/

**Comment by zach1590** [comment]
rebased the branch to catch up with all the changes on develop
Added a section to docker compose file and a new docker file that does the work of running the unit tests under docker
Also added a section to the readme to explain how to run the tests, what tests are available and the roadmap for future tests

**Pull request merged**
